src/Entity/ProductImage.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductImageRepository; 

/**
 * @ORM\Entity(repositoryClass=ProductImageRepository::class) 
 */
class ProductImage
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
 
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_size;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class, inversedBy="productImages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;
 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getImageSize(): ?string
    {
        return $this->image_size;
    }

    public function setImageSize(string $image_size): self
    {
        $this->image_size = $image_size;

        return $this;
    }

    public function getProduct(): ?Produit
    {
        return $this->product;
    }

    public function setProduct(?Produit $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getImageFile():?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): void
    {
        $this->imageFile = $imageFile; 
        if(null != $this->imageFile){
            $this->updated_at = new \DateTime('now');
        } 
    }

 
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;  
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert; 

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)  
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("product:read")
     */
    private $id;
   
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10,max=255, minMessage="Votre message est bien court")  
     * @Groups("product:read")
     */
    private $title;

    /**
     * @ORM\Column(type="text", length=255)
     * @Assert\Length(min=7, max=255) 
     * @Groups("product:read")
     */
    private $description;
  
    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5, max=255)
     * @Groups("product:read")
     */
    private $reference;

    /**
     * @ORM\Column(type="float")
     * @Groups("product:read")
     */
    private $prix;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     * @Groups("product:read")
     */
    private $category;

    /**
     * @ORM\OneToMany(targetEntity=ProductImage::class, mappedBy="product", cascade={"persist"})
     */
    private $productImages; 
 

    public function __construct(){ 
        $productImages = new ArrayCollection();
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function formattedPrice(){
        return  number_format($this->prix, 0,'',' ');
    }
    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    } 
 
    /**
     * @return Collection|ProductImage[]
     */
    public function getProductImages(): Collection
    {
        return $this->productImages;
    }

    public function addProductImage(ProductImage $productImage): self
    {     
        //if (!$this->productImages->contains($productImage)) { 
            $this->productImages[] = $productImage;
            $productImage->setProduct($this);
        //}

        return $this;
    }

    public function removeProductImage(ProductImage $productImage): self
    {
        if ($this->productImages->removeElement($productImage)) {
            // set the owning side to null (unless already changed)
            if ($productImage->getProduct() === $this) {
                $productImage->setProduct(null);
            }
        }

        return $this;
    }

}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Entity\Category;
use App\Entity\SearchProduit;
use App\Form\ProduitFormType;
use App\Form\SearchProduitType;
use App\Repository\ProduitRepository; 
use App\Repository\CategoryRepository; 
use JMS\Serializer\SerializerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route; 
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
  


#[Route('/stock')]
class ProduitController extends AbstractController
{   

    public function __construct(EntityManagerInterface $manager, ProduitRepository $repository ){
        $this->manager = $manager;
        $this->repository = $repository; 
    }

    #[Route('/', name: 'home')]
    public function accueil(){ 
        $Latestproducts = $this->repository->findAllLatestProducts();
        return $this->render('produit/accueil.html.twig',[  
            'products' => $Latestproducts,
        ]);
    }
    
    #[Route('/product', name: 'product.index')]
    public function product(Request $request){ 

        $search = new SearchProduit();
        $form = $this->createForm(SearchProduitType::class, $search);
        $form->handleRequest($request); 

        $Allproducts = $this->repository->findAllProducts($search);

        return $this->render('produit/index.html.twig',[  
            'products' => $Allproducts,
            'form' => $form->createView(),
        ]);
    }
    
    
    #[Route('/{id}', name:'product.show')]
    public function showProduit(Produit $produit): Response{ 
        return $this->render('produit/show.html.twig',[
            'product' => $produit
        ]);
    } 
  

    #[Route('/categories', name: 'categories')]
    public function showCategories(CategoryRepository $categoryRepository){
        $categories = $categoryRepository->findAll();
        return $this->render('category/showC.html.twig',[ 
            'categories'=>$categories
        ]);
    }
    
    
  
    #[Route('/category/{id}', name:'show_category_info')]
    public function showCategoryInfo(Category $category,CategoryRepository $categoryRepository){  
        return $this->render('category/showInfo.html.twig',[
            'category' => $category
        ]);
    }
    
    #[Route('/cat/{id}', name:'delete_category')]
    public function deleteCategory(Category $category,CategoryRepository $categoryRepository, EntityManagerInterface $manager){ 
       
        $this->deleteProduitByCategoryId($category, $manager);
        
        $manager->remove($category); 

        $manager -> flush();
        return $this->redirectToRoute('categories');
    }

    // #[Route('/cat/{id}', name:'delete_category')]
    // public function deleteCategoryById(Category $category, EntityManagerInterface $manager){  
    //     dump($category);
    //     $manager -> remove($category);
    //     $manager -> flush();

    //     return $this->redirectToRoute('category');
    // } 
    
    
    #[Route('/delete/category/{id}', name:'delete_produit_by_catId')]
    public function deleteProduitByCategoryId(Category $category ,EntityManagerInterface $manager){
        
        $res =  $this->getDoctrine()
                    ->getRepository(Produit::class) 
                    ->deleteByCategoryId($category->getId());

        $manager->flush(); 
        return $this->redirectToRoute('categories');
    }
    
    #[Route('/product/{id}', name:'show_product')]
    public function showProduct($id){
        $product = $this->getDoctrine()->getRepository(Produit::class)->findOneById($id);
         
        if(empty($product)){
            $response = array (
                'code' => -1,
                'message' => 'produict not found',
                'error' => null,
                'result' => null
            );
        
            return new JsonResponse($response, Response::HTTP_NOT_FOUND);
        }
         
         
        return $this->json($product,200,[],['groups' => ['product:read']]);
    }

    #[Route("/api/create/product", name:"create_product")]
    public function createProduct(Request $request){
        $data = $request->getContent();

        $product = $this->get('serializer')->deserialize($data, 'App\Entity\Produit', 'json');

        // $reponse = $validate->validateRequest($product);

        // if(!empty($reponse)){
        //     return new JsonResponse($reponse, Response::HTTP_BAD_REQUEST);
        // }
            
        $cat = $this->getDoctrine()->getRepository(Category::class)->findOneByTitle($product->getCategory()->getTitle());
        $product->setCategory($cat);
        $this->manager->persist($product);
        $this->manager->flush();

        $response = array(
            'code' =>1,
            'message' =>'Product created',
            'errors' => null,
            'result' =>null
        );

        return new JsonResponse($response, Response::HTTP_CREATED);
    } 
    
}

templates/produit/accueil.html.twig
{% extends 'base.html.twig' %}

{% block body %} 

    <div class="jumbotron text-center">
        <h2 class=" text-info text-capitalize display-5" style="color:#077E8A" >Gestion des produits</h2> 
    </div>
    <div class="container mt-4"> 
    <h2 style="color:#077E8A">Latest Product</h2>
    <div class="row mt-5 mb-5">
        {% for product in products %} 
              <div class="col-md-3">    
                 <div class="card border border-light rounded-lg mt-1" style="height:370px; background-color:#ecf0f1 ">
                 <div class="card-title m-2 text-center"> <h4 ><a  style="color:#077E8A" class="text-decoration-none" href="{{ path('product.show', {'id': product.id}) }}">{{ product.title}}</a></h4></div>

                     {% if product.productImages is not empty %}
                      <div class="card-img-top p-2">
                             <div id="carouselExampleControls{{product.id}}" class="carousel slide" data-bs-ride="carousel">
                              <div class="carousel-inner">
                              {% set value = true %} 
                                {% for image in product.productImages %}    
                                <div class="carousel-item  {% if value %} active {% endif %}">
                                  <img src="/uploads/{{image.imageName}}" class="d-block w-100" alt="..." height="170px" width="300px">
                                </div>  
                                {% set value = false %}
                                {% endfor %}
                              </div>
                              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls{{product.id}}" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                              </button>
                              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls{{product.id}}" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                              </button>
                            </div>
                      </div>
                      
                   {% else %} 
                     <img src="/uploads/default_image.png" class="d-block w-100" alt="..." height="300px">
                   {% endif %}
                    <div class="card-body  d-flex flex-column align-items-baseline">
                            <div class="text-capitalize ">{{product.description}}</div>
                            <p   style="color:#077E8A"><b>{{product.prix}}$</b></p> 
                    </div>
                 </div>
             </div>   
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/produit/create.html.twig
{% extends 'base.html.twig' %} 
{% block body %}
    <div class="container mt-5">
        <h3 class=" display-5 text-center">
        
         {% if editMode %}
                Modification de Produit
         {% else %}
                Création de produit
         {% endif %}
        </h3> 
        {{form_start(formProduit)}}
        <div class="row align-items-end">
            <div class="col-md-6">{{form_row(formProduit.title)}}</div>
            <div class="col-md-3">{{form_row(formProduit.reference)}}</div> 
            <div class="col-md-3"> {{form_row(formProduit.productImages)}}</div> 
        </div>
        
        <div class="row"> 
            <div class="col-md-3">{{form_row(formProduit.prix)}}</div>
            <div class="col-md-9">{{form_row(formProduit.category)}}</div> 
        </div>

        <div class="row">
            <div class="col-md-12">{{form_row(formProduit.description)}}</div>
        </div>

         {% if editMode %}
            <div class="card"> 
              <div class="card-header fs-5" style="color:#077E8A"> Modifier les images de produit</div>
              <div class="card-body">
                <div class="row text-center">
                {% for image in produit.productImages %}
                    <div class="col-md-3">
                     <img src="/uploads/{{image.imageName}}" class="d-block w-100" alt="..." height="170px">
                     <a href="{{path('product.delete_image',{'id': image.id})}}" class="text-danger text-decoration-none fs-6 fw-normal" >Delete Image</a>
                    </div>
                {% endfor %}
             </div>
              </div>
            </div>
        {% endif %}

        <div class="text-left mb-5 mt-4"> 
                <button type="submit" class="btn btn-danger">
                    {% if editMode %}
                        Update
                    {% else %}
                        Enregistrer
                    {% endif %}
                </button> 
        </div>
         {{form_end(formProduit)}}

       
        <a class="btn btn-primary mt-5" href="{{ path('manage') }}">Voir list des categories</a> 
    </div>
{% endblock %}      

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProduitController!{% endblock %}

{% block body %} 
        <div class="jumbotron text-center">
            <div class="container"> 
                  {{form_start(form)}}
                  <div class="form-row align-items-end">
                      <div class="col-4">{{form_row(form.minPrice)}}</div>
                      <div class="col-4">{{form_row(form.maxPrice)}}</div> 
                      <div class="col-2 form-group"><button class="btn btn-success">Search</button></div>
                  </div>
                  <div class="row">
                    <div class="col-8">{{form_row(form.categories)}}</div>
                  </div>
                 {{form_end(form)}} 
            </div>
        </div> 
        <div class="container mt-4">
        {% if products is not empty %}
           <h2 style="color:#077E8A">List Of Products</h2>
           <div class="row mt-4"> 
           <div class="card-deck">
            {% for product in products %}  
             <div class="col-md-3">    
                 <div class="card border border-light rounded-lg m-0 mt-1" style="height:370px; background-color:#ecf0f1 ">
                 <div class="card-title m-2 text-center"> <h4 ><a  style="color:#077E8A" class="text-decoration-none" href="{{ path('product.show', {'id': product.id}) }}">{{ product.title}}</a></h4></div>

                     {% if product.productImages is not empty %}
                      <div class="card-img-top p-2">
                             <div id="carouselExampleControls{{product.id}}" class="carousel slide" data-bs-ride="carousel">
                              <div class="carousel-inner">
                              {% set value = true %} 
                                {% for image in product.productImages %}    
                                <div class="carousel-item  {% if value %} active {% endif %}">
                                  <img src="/uploads/{{image.imageName}}" class="d-block w-100" alt="..." height="170px" width="300px">
                                </div>  
                                {% set value = false %}
                                {% endfor %}
                              </div>
                              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls{{product.id}}" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                              </button>
                              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls{{product.id}}" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                              </button>
                            </div>
                      </div>
                      
                   {% else %} 
                     <img src="/uploads/default_image.png" class="d-block w-100" alt="..." height="300px">
                   {% endif %}
                    <div class="card-body  d-flex flex-column align-items-baseline">
                            <div class="text-capitalize ">{{product.description}}</div>
                            <p   style="color:#077E8A"><b>{{product.prix}}$</b></p> 
                    </div>
                 </div>
             </div>  
            {% endfor %}
            </div>
           </div>
        {% endif %}
           <a href="{{path('home')}}" class="btn btn-success mb-3 mt-3">Back Home</a>
        </div> 
{% endblock %}
 {# {% for image in product.productImages %} 
                                      <img src="/uploads/{{ image.imageName}}" class="d-block w-100" alt="..."> 
                              {% endfor %}  #}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}
{% block body %} 
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8 d-flex justify-content-center">
                         <div class="card-img-top" style="width:50%">
                         {% if product.productImages is not empty %}
                             <div id="carouselExampleControls"  class="carousel slide" data-bs-ride="carousel">
                             <div class="carousel-indicators">
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                            </div>
                              <div class="carousel-inner">
                              {% set value = true %} 
                                {% for image in product.productImages %}    
                                <div class="carousel-item  {% if value %} active {% endif %}">
                                  <img src="/uploads/{{image.imageName}}" class="d-block w-100" alt="..." height="300px">
                                </div>  
                                {% set value = false %}
                                {% endfor %}
                              </div>
                              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                              </button>
                              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                              </button>
                            </div>
                       {% else %} 
                             <img src="/uploads/default_image.png" class="d-block w-100" alt="..." height="300px">
                        {% endif %}
                      </div>          
            </div>
            <dvi class="col-md-4">
                <h1 class="text-info">{{product.title}}</h1>
                <p>{{product.description}}</p>
                <h3 class="text-info">{{product.prix}}$</h3>
            </dvi>
        </div>
    </div>
    <div class="container">
        <h3>Informations</h3>
        <div class="row">
            <div class="col-md-8">
                <table class="table table-hover table-striped">
                    <tr>
                        <th>Title</th>
                        <td>{{product.title}}</td>
                    </tr>
                     <tr>
                        <th>Reference</th>
                        <td>{{product.reference}}</td>
                    </tr>
                     <tr>
                        <th>Description</th>
                        <td>{{product.description}}</td>
                    </tr>
                     <tr>
                        <th>Price</th>
                        <td>{{product.formattedPrice}} $</td>
                    </tr>
                    <tr>
                        <th>Category</th>
                        <td>{{product.category.title}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <a href=" {{ path('product.index') }} "  class="btn btn-primary">Back To List</a>
    </div> 

    
{% endblock %}